# Generated by Django 4.1.1 on 2022-10-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teammember_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=100, verbose_name='Service')),
                ('description', models.TextField(max_length=250, verbose_name='Description')),
                ('icon', models.CharField(choices=[('lni-rocket', 'rocket'), ('lni-laptop-phone', 'laptop'), ('lni-cog', 'cog'), ('lni-leaf', 'leaf'), ('lni-layers', 'layers')], max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
