# Generated by Django 4.1.2 on 2022-10-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='description',
        ),
    ]
